In [1]:
##Exporting Data with SL API
# Author: Santosh Kumar Udayakumar
# Script :Inspect and explore the SL API and SL Netex file and assess what is the best data source and download the data files to the source directory 

import requests
import zipfile
import io
import pandas as pd

# Replace with your actual API key
api_key = '<REPLACE_API_KEY>'
url = f'https://opendata.samtrafiken.se/gtfs-sweden/sweden.zip?key={api_key}'
response = requests.get(url)
if response.status_code == 200:
    # Step 2: Extract the ZIP file
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        z.extractall('gtfs_data')  # Extract to a folder named 'gtfs_data'
else:
    print("Failed to download the data:", response.status_code)

In [4]:
import os
gtfs_data_path = 'gtfs_data'

# List the files in the directory
files = os.listdir(gtfs_data_path)

# Print the list of files
for file in files:
    print(file)

transfers.txt
agency.txt
calendar_dates.txt
stop_times.txt
shapes.txt
trips.txt
feed_info.txt
attributions.txt
stops.txt
calendar.txt
routes.txt

In [2]:
transfers_df=pd.read_csv('gtfs_data/transfers.txt')
agency_df=pd.read_csv('gtfs_data/agency.txt')
calendar_dates_df=pd.read_csv('gtfs_data/calendar_dates.txt')
stop_times_df = pd.read_csv('gtfs_data/stop_times.txt')
shapes_df = pd.read_csv('gtfs_data/shapes.txt')
trips_df = pd.read_csv('gtfs_data/trips.txt')
feed_info = pd.read_csv('gtfs_data/feed_info.txt')
attributions = pd.read_csv('gtfs_data/attributions.txt')
stops_df = pd.read_csv('gtfs_data/stops.txt')
calendar_df = pd.read_csv('gtfs_data/calendar.txt')
routes_df = pd.read_csv('gtfs_data/routes.txt')


# Display the first few rows of each DataFrame
print("Stops Data:")
print(stops_df.head())

print("\nRoutes Data:")
print(routes_df.head())

print("\nTrips Data:")
print(trips_df.head())

Stops Data:
   stop_id                 stop_name   stop_lat   stop_lon  location_type  \
0        1  Stockholm Centralstation  59.331537  18.054943              1
1        2   Göteborg Centralstation  57.709299  11.973659              1
2        3      Malmö Centralstation  55.608777  13.000216              1
3        4           Alvesta station  56.898911  14.556790              1
4        5    Uppsala Centralstation  59.857769  17.647454              1

   parent_station platform_code
0             NaN           NaN
1             NaN           NaN
2             NaN           NaN
3             NaN           NaN
4             NaN           NaN

Routes Data:
           route_id           agency_id route_short_name route_long_name  \
0  9011001000100000  505000000000000001                1             NaN
1  9011001000200000  505000000000000001                2             NaN
2  9011001000300000  505000000000000001                3             NaN
3  9011001000400000  505000000000000001                4             NaN
4  9011001001000000  505000000000000001               10      Blå linjen

   route_type  route_desc
0         700         NaN
1         700         NaN
2         700         NaN
3         700         NaN
4         401         NaN

Trips Data:
           route_id  service_id            trip_id  trip_headsign  \
0  9011001000100000           1  14010000664276697            NaN
1  9011001000100000           1  14010000664277107            NaN
2  9011001000100000           1  14010000664278217            NaN
3  9011001000100000           1  14010000664280135            NaN
4  9011001000100000           1  14010000664282897            NaN

   direction_id             shape_id
0             1  1014010000482329256
1             1  1014010000482329256
2             1  1014010000482329256
3             1  1014010000482329256
4             1  1014010000482329256

In [9]:
agency_df

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
0,505000000000000603,Kommuner i Stockholms Län,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
1,505000000000000601,X-Trafik Kundtjänst,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
2,505000000000000600,Storstockholms Lokaltrafik AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
3,505000000000000607,AB SL Kundtjänst,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
4,505000000000000606,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
...,...,...,...,...,...,...
94,505000000000000690,Flixbus,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
95,505000000000000689,Vy Buss AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
96,505000000000000688,Västra Götalands län,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
97,505000000000000697,Länstrafiken Norrbotten,https://www.resrobot.se/,Europe/Stockholm,sv,NaN
98,505000000000000696,Luleå Lokaltrafik,https://www.resrobot.se/,Europe/Stockholm,sv,NaN

In [11]:
stops_df

,stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station,platform_code
0,1,Stockholm Centralstation,59.331537,18.054943,1,NaN,NaN
1,2,Göteborg Centralstation,57.709299,11.973659,1,NaN,NaN
2,3,Malmö Centralstation,55.608777,13.000216,1,NaN,NaN
3,4,Alvesta station,56.898911,14.556790,1,NaN,NaN
4,5,Uppsala Centralstation,59.857769,17.647454,1,NaN,NaN
...,...,...,...,...,...,...,...
168926,9023001022111001,Brevik,59.348652,18.205307,2,9465.0,NaN
168927,9023001022121001,Käppala,59.352790,18.218578,2,9466.0,NaN
168928,9023001022131001,Talludden,59.355633,18.222192,2,9467.0,NaN
168929,9023001022142001,Gåshaga,59.356953,18.228934,2,12734.0,NaN
168930,9023001022151001,Gåshaga brygga,59.357089,18.232233,2,11030.0,NaN

In [19]:
###Lookup latest SL data and Place in the source Directory

import requests

# Replace with your actual operator and API key
operator = 'sl'  # Example operator
apikey = '<Replace API KEY>'        # Example API key

# Construct the URL
url = f"https://opendata.samtrafiken.se/netex/{operator}/{operator}.zip?key={apikey}"

# Make the GET request
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Save the content to a file
    with open(f"{operator}.zip", 'wb') as file:
        file.write(response.content)
    print(f"Downloaded {operator}.zip")
else:
    print(f"Failed to retrieve data: {response.status_code} - {response.text}")

Downloaded sl.zip

In [20]:
if response.status_code == 200:
    # Step 2: Extract the ZIP file
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        z.extractall('sl_data')  # Extract to a folder named 'gtfs_data'
else:
    print("Failed to download the data:", response.status_code)

In [21]:
pip install pandas lxml

Requirement already satisfied: pandas in /usr/local/Cellar/jupyterlab/4.0.9_1/libexec/lib/python3.12/site-packages (2.1.3)
Collecting lxml
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/bd/83/26b1864921869784355459f374896dcf8b44d4af3b15d7697e9156cb2de9/lxml-5.3.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata
  Downloading lxml-5.3.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy<2,>=1.26.0 in /usr/local/Cellar/jupyterlab/4.0.9_1/libexec/lib/python3.12/site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/opt/python-dateutil/lib/python3.12/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/Cellar/jupyterlab/4.0.9_1/libexec/lib/python3.12/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/Cellar/jupyterlab/4.0.9_1/libexec/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/opt/six/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading lxml-5.3.0-cp312-cp312-macosx_10_9_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 8.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Installing collected packages: lxml
Successfully installed lxml-5.3.0

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.0.9_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.